import { useEffect, useState } from 'react'
import { useLocation, useNavigate } from 'react-router-dom'
import { HeroSection } from '../components/home/HeroSection'
import { JournalSection } from '../components/home/JournalSection'
import { ShoppingList } from '../components/home/ShoppingList'
import { WeeklyMenu } from '../components/home/WeeklyMenu'
import { Footer } from '../components/home/Footer'
import { BookHeart, CirclePlus, Check, Clock3, Leaf, X } from '../components/ui/icons'
import { createMeal, getWeeklyMenu, updateMeal } from '../services/weeklyMenuService'

const initialMenu = Object.fromEntries(['Lunes', 'Martes', 'Miércoles', 'Jueves', 'Viernes', 'Sábado', 'Domingo'].map((day) => [day, { Desayuno: null, Almuerzo: null, Merienda: null, Cena: null }]))
const weekdays = Object.keys(initialMenu)
const motivationalPhrases = ['¡Un día a la vez! Cada elección consciente es un paso más hacia sentirte excelente.', 'Cuidar tu panza también es una forma de quererte. ¡Hoy va a ser un gran día!', 'La paciencia es la mejor receta del menú. ¡Vas muy bien!', 'Tu cuerpo se está reacomodando. Dale tiempo, amor y buena comida.']

function getMealName(meal) { return typeof meal === 'string' ? meal : meal?.name || '' }
function getMealIngredients(meal) { return Array.isArray(meal?.ingredients) ? meal.ingredients : [] }
function getShoppingItems(menu) { const grouped = new Map(); Object.values(menu).forEach((day) => Object.values(day).forEach((meal) => getMealIngredients(meal).forEach((ingredient) => { const name = ingredient.trim(); if (!name) return; const key = name.toLocaleLowerCase(); const current = grouped.get(key); grouped.set(key, current ? { ...current, count: current.count + 1 } : { name, count: 1 }) }))); return [...grouped.values()] }
function getMonday(date) { const monday = new Date(date); monday.setHours(0, 0, 0, 0); const day = monday.getDay(); monday.setDate(monday.getDate() - ((day + 6) % 7)); return monday }
function addDays(date, amount) { const result = new Date(date); result.setDate(result.getDate() + amount); return result }
function formatWeekRange(start) { const end = addDays(start, 6); const startMonth = start.toLocaleDateString('es-ES', { month: 'long' }); const endMonth = end.toLocaleDateString('es-ES', { month: 'long' }); return startMonth === endMonth ? `${start.getDate()} — ${end.getDate()} de ${endMonth}` : `${start.getDate()} de ${startMonth} — ${end.getDate()} de ${endMonth}` }
function formatDayName(date) { return date.toLocaleDateString('es-ES', { weekday: 'short' }).replace('.', '') }
function formatMonthShort(date) { return date.toLocaleDateString('es-ES', { month: 'short' }).replace('.', '').toUpperCase() }
function formatJournalDate(date) { return date.toLocaleDateString('es-ES', { day: 'numeric', month: 'long', year: 'numeric' }) }
function formatDateKey(date) { return [date.getFullYear(), String(date.getMonth() + 1).padStart(2, '0'), String(date.getDate()).padStart(2, '0')].join('-') }
function menuFromRows(rows, weekStart) { const menu = Object.fromEntries(weekdays.map((day) => [day, { ...initialMenu[day] }])); const mealNames = { desayuno: 'Desayuno', almuerzo: 'Almuerzo', merienda: 'Merienda', cena: 'Cena' }; rows.forEach((row) => { const dayIndex = Array.from({ length: 7 }, (_, index) => formatDateKey(addDays(weekStart, index))).indexOf(row.date); const mealName = mealNames[String(row.mealType).toLowerCase()]; if (dayIndex >= 0 && mealName) menu[weekdays[dayIndex]][mealName] = { id: row.id, name: row.name, ingredients: row.ingredients } }); return menu }

function WeeklyCalendar({ menu, weekStart, days, onAddMeal }) {
  const [activeDay, setActiveDay] = useState('Lunes'); const activeMeals = menu[activeDay] || {}; const activeDate = addDays(weekStart, days.indexOf(activeDay))
  return <section id="menu" className="weekly-calendar mb-6 rounded-3xl border border-ink/10 bg-white p-4 shadow-soft dark:border-cream/10 dark:bg-ink-soft dark:shadow-soft-dark sm:p-6"><div className="mb-6 flex items-center justify-between gap-4"><div><h2 className="font-display text-2xl">Menú semanal</h2><p className="mt-1 text-sm text-ink/50 dark:text-cream/50">Elige un día para ver sus comidas.</p></div><button onClick={() => onAddMeal({ day: activeDay })} className="flex shrink-0 items-center gap-2 rounded-full bg-sage px-4 py-2.5 text-xs font-bold text-moss dark:bg-moss/30 dark:text-sage"><CirclePlus size={15} /> <span className="hidden sm:inline">Agregar comida</span><span className="sm:hidden">Agregar</span></button></div><div role="tablist" aria-label="Días de la semana" className="-mx-1 grid grid-cols-7 gap-2 px-1 pb-2">{days.map((day, index) => { const date = addDays(weekStart, index); const isActive = day === activeDay; return <button key={day} role="tab" aria-selected={isActive} aria-controls={`meals-${day}`} onClick={() => setActiveDay(day)} className={`flex min-h-[68px] flex-col items-center justify-center gap-1 rounded-full border px-1 py-2 transition ${isActive ? 'border-moss bg-moss text-white shadow-lg shadow-moss/20' : 'border-ink/10 bg-cream text-ink/60 hover:border-moss/40 hover:text-moss dark:border-cream/10 dark:bg-ink dark:text-cream/60 dark:hover:border-moss/40 dark:hover:text-sage'}`}><span className="text-[10px] font-bold uppercase tracking-wider">{day.slice(0, 3)}</span><span className={`grid h-7 min-w-7 place-items-center rounded-full px-2 text-sm font-semibold leading-none ${isActive ? 'bg-sun/95 text-moss' : 'bg-white/80 text-ink dark:bg-ink-soft dark:text-cream'}`}>{date.getDate()}</span></button> })}</div><div id={`meals-${activeDay}`} role="tabpanel" className="mt-6 border-t border-ink/10 pt-5 dark:border-cream/10"><div className="mb-4 flex items-center justify-between"><h3 className="font-display text-2xl text-moss dark:text-sage">{activeDay}</h3><span className="text-xs font-bold uppercase tracking-wider text-ink/35 dark:text-cream/35">{activeDate.toLocaleDateString('es-ES', { day: 'numeric', month: 'long' })}</span></div><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{Object.entries(activeMeals).map(([meal, value]) => { const mealName = getMealName(value); return <button onClick={() => onAddMeal({ day: activeDay, meal })} key={meal} className={`meal-card group text-left ${mealName ? 'meal-card--filled' : ''}`}><span className="mb-1.5 block text-[10px] font-bold uppercase tracking-wider text-ink/40 dark:text-cream/40">{meal}</span><span className={`block text-sm font-semibold leading-snug ${mealName ? 'group-hover:text-coral' : 'text-moss dark:text-sage'}`}>{mealName || '+ Agregar comida'}</span>{mealName && <span className="mt-1.5 flex items-center gap-1 text-[10px] text-ink/40 dark:text-cream/40"><Clock3 size={11} /> Ver comida</span>}</button> })}</div></div></section>
}

function MealModal({ target, days, onClose, onSubmit, error }) { return <div className="fixed inset-0 z-20 grid place-items-center bg-ink/50 p-4 backdrop-blur-sm"><div className="w-full max-w-lg rounded-3xl bg-cream p-6 shadow-2xl dark:bg-ink-soft dark:text-cream sm:p-8"><div className="mb-6 flex items-start justify-between"><div><span className="mb-3 inline-flex rounded-full bg-sage p-2 text-moss dark:bg-moss/30 dark:text-sage"><CirclePlus size={18} /></span><h2 className="font-display text-3xl">Agregar comida</h2><p className="mt-1 text-sm text-ink/50 dark:text-cream/50">Completa tu menú a tu manera.</p></div><button onClick={onClose} className="rounded-full p-2 hover:bg-black/5 dark:hover:bg-cream/10" aria-label="Cerrar"><X size={20} /></button></div><form onSubmit={onSubmit} className="space-y-5"><label className="block text-sm font-bold">Día<select name="day" defaultValue={target.day} className="field mt-2">{days.map((day) => <option key={day}>{day}</option>)}</select></label><label className="block text-sm font-bold">Momento<select name="meal" defaultValue={target.meal || 'Cena'} className="field mt-2"><option>Desayuno</option><option>Almuerzo</option><option>Merienda</option><option>Cena</option></select></label><label className="block text-sm font-bold">Nombre de la receta<input autoFocus required name="name" defaultValue={target.recipe?.name || ''} className="field mt-2" placeholder="Ej. Ensalada de pollo y quinoa" /></label><label className="block text-sm font-bold">Ingredientes <span className="font-normal text-ink/40 dark:text-cream/40">(separados por comas)</span><textarea required name="ingredients" defaultValue={target.recipe?.ingredients?.join(', ') || ''} className="field mt-2 min-h-24" placeholder="Ej. tomate, lechuga, pollo" /></label>{error && <p className="rounded-xl bg-coral/10 p-3 text-sm text-coral">{error}</p>}<button type="submit" className="w-full rounded-full bg-moss py-3.5 text-sm font-bold text-white">Guardar en el menú</button></form></div></div> }

export function HomePage() {
  const location = useLocation(); const navigate = useNavigate(); const [menu, setMenu] = useState(initialMenu); const shoppingItems = getShoppingItems(menu); const [weekStart, setWeekStart] = useState(() => getMonday(new Date())); const [menuLoading, setMenuLoading] = useState(true); const [menuError, setMenuError] = useState(''); const [checked, setChecked] = useState([]); const [mealTarget, setMealTarget] = useState(null); const [journalText, setJournalText] = useState(''); const [copied, setCopied] = useState(false); const [showMotivation, setShowMotivation] = useState(true); const [motivationalPhrase] = useState(() => motivationalPhrases[Math.floor(Math.random() * motivationalPhrases.length)]); const [journalEntries, setJournalEntries] = useState(() => { try { return JSON.parse(localStorage.getItem('sibo-journal') || '[]') } catch { return [] } }); const [theme, setTheme] = useState(() => { try { return localStorage.getItem('sibo-theme') || 'light' } catch { return 'light' } })
  useEffect(() => { if (location.state?.recipeToAdd) { setMealTarget({ day: 'Lunes', meal: 'Cena', recipe: location.state.recipeToAdd }); navigate('/', { replace: true, state: null }) } }, [location.state, navigate])
  useEffect(() => { let active = true; setMenuLoading(true); setMenuError(''); getWeeklyMenu({ startDate: formatDateKey(weekStart), endDate: formatDateKey(addDays(weekStart, 6)) }).then((rows) => { if (active) setMenu(menuFromRows(rows, weekStart)) }).catch((loadError) => { if (active) setMenuError(loadError.message) }).finally(() => { if (active) setMenuLoading(false) }); return () => { active = false } }, [weekStart])
  useEffect(() => { localStorage.setItem('sibo-journal', JSON.stringify(journalEntries)) }, [journalEntries]); useEffect(() => { document.documentElement.classList.toggle('dark', theme === 'dark'); try { localStorage.setItem('sibo-theme', theme) } catch {} }, [theme]); useEffect(() => { const timer = window.setTimeout(() => setShowMotivation(false), 4500); return () => window.clearTimeout(timer) }, [])
  const persistMeal = async ({ day, meal, name, ingredients }) => { const dayIndex = weekdays.indexOf(day); const currentMeal = menu[day]?.[meal]; const savedMeal = currentMeal?.id ? await updateMeal({ id: currentMeal.id, date: formatDateKey(addDays(weekStart, dayIndex)), mealType: meal.toLowerCase(), recipeName: name, ingredients }) : await createMeal({ date: formatDateKey(addDays(weekStart, dayIndex)), mealType: meal.toLowerCase(), recipeName: name, ingredients }); setMenu((current) => ({ ...current, [day]: { ...current[day], [meal]: savedMeal } })) }
  const saveManualMeal = async (event) => { event.preventDefault(); const form = new FormData(event.currentTarget); const day = form.get('day'); const meal = form.get('meal'); const name = form.get('name')?.trim(); const ingredients = form.get('ingredients')?.split(',').map((ingredient) => ingredient.trim()).filter(Boolean); if (!name) return; setMenuError(''); try { await persistMeal({ day, meal, name, ingredients }); setMealTarget(null) } catch (saveError) { setMenuError(saveError.message) } }
  const saveJournalEntry = (event) => { event.preventDefault(); const text = journalText.trim(); if (!text) return; setJournalEntries((current) => [{ id: Date.now(), text, date: formatJournalDate(new Date()) }, ...current]); setJournalText('') }
  const copyShoppingList = async () => { if (!shoppingItems.length) return; const text = `Lista de compras · sibo.decis\n${shoppingItems.map((item) => `- ${item.name}${item.count > 1 ? ` x${item.count}` : ''}`).join('\n')}`; try { await navigator.clipboard.writeText(text) } catch { const fallback = document.createElement('textarea'); fallback.value = text; document.body.appendChild(fallback); fallback.select(); document.execCommand('copy'); document.body.removeChild(fallback) } setCopied(true); window.setTimeout(() => setCopied(false), 2000) }
  return <div className="min-h-screen bg-cream text-ink dark:bg-ink-dark dark:text-cream">{showMotivation && <div className="fixed inset-0 z-50 grid place-items-center bg-cream px-6 text-center text-ink dark:bg-ink-dark dark:text-cream"><div><span className="mb-7 grid h-16 w-16 place-items-center rounded-2xl bg-moss text-cream"><Leaf size={30} /></span><p className="mb-5 text-xs font-bold uppercase tracking-[.22em] text-coral">sibo<span className="text-ink/30 dark:text-cream/30">.</span>decis</p><blockquote className="font-display text-4xl leading-tight sm:text-5xl">“{motivationalPhrase}”</blockquote></div></div>}<main id="inicio" className="mx-auto max-w-[1440px] px-5 pb-20 pt-10 lg:px-10 lg:pt-16"><HeroSection weekStart={weekStart} formatWeekRange={formatWeekRange} onPreviousWeek={() => setWeekStart((current) => addDays(current, -7))} onNextWeek={() => setWeekStart((current) => addDays(current, 7))} />{menuLoading && <p className="mb-4 text-sm text-ink/50 dark:text-cream/50">Cargando tu menú...</p>}{menuError && <p className="mb-4 rounded-xl bg-coral/10 px-4 py-3 text-sm text-coral">No pudimos cargar el menú guardado: {menuError}</p>}<WeeklyCalendar menu={menu} weekStart={weekStart} days={weekdays} onAddMeal={setMealTarget} /><div className="grid gap-6 xl:grid-cols-[1fr_310px]"><WeeklyMenu menu={menu} weekStart={weekStart} weekdays={weekdays} onAddMeal={setMealTarget} getMealName={getMealName} formatDayName={formatDayName} formatMonthShort={formatMonthShort} /><ShoppingList shoppingItems={shoppingItems} checked={checked} toggleItem={(name) => setChecked((current) => current.includes(name) ? current.filter((item) => item !== name) : [...current, name])} onCopy={copyShoppingList} copied={copied} /></div><JournalSection journalText={journalText} onJournalTextChange={(event) => setJournalText(event.target.value)} onSave={saveJournalEntry} journalEntries={journalEntries} /></main><Footer />{mealTarget && <MealModal target={mealTarget} days={weekdays} onClose={() => setMealTarget(null)} onSubmit={saveManualMeal} error={menuError} />}</div>
}
