import { BookHeart, X } from '../ui/icons'

function toFieldValue(value) {
  return Array.isArray(value) ? value.join('\n') : value || ''
}

export function RecipeFormModal({ recipe, onClose, onSubmit, loading, error }) {
  const isEditing = Boolean(recipe)

  return <div className="fixed inset-0 z-20 grid place-items-center bg-ink/50 p-4 backdrop-blur-sm"><div className="max-h-[90vh] w-full max-w-lg overflow-y-auto rounded-3xl bg-cream p-6 shadow-2xl dark:bg-ink-soft dark:text-cream sm:p-8"><div className="mb-6 flex items-start justify-between"><div><span className="mb-3 inline-flex rounded-full bg-sage p-2 text-moss dark:bg-moss/30 dark:text-sage"><BookHeart size={18} /></span><h2 className="font-display text-3xl">{isEditing ? 'Editar receta' : 'Agregar receta'}</h2><p className="mt-1 text-sm text-ink/50 dark:text-cream/50">Guarda tus ingredientes y pasos para volver a encontrarlos.</p></div><button onClick={onClose} className="rounded-full p-2 hover:bg-black/5 dark:hover:bg-cream/10" aria-label="Cerrar"><X size={20} /></button></div><form onSubmit={onSubmit} className="space-y-5"><label className="block text-sm font-bold">Nombre de la receta<input autoFocus required name="name" defaultValue={recipe?.name || ''} className="field mt-2" placeholder="Ej. Ensalada de pollo y quinoa" /></label><label className="block text-sm font-bold">Descripción <span className="font-normal text-ink/40 dark:text-cream/40">(opcional)</span><textarea name="description" defaultValue={recipe?.description || ''} className="field mt-2 min-h-20" placeholder="Una breve descripción de tu receta" /></label><label className="block text-sm font-bold">Ingredientes <span className="font-normal text-ink/40 dark:text-cream/40">(uno por línea)</span><textarea required name="ingredients" defaultValue={toFieldValue(recipe?.ingredients)} className="field mt-2 min-h-28" placeholder={'Ej.\npollo\narroz\nzanahoria'} /></label><label className="block text-sm font-bold">Preparación <span className="font-normal text-ink/40 dark:text-cream/40">(un paso por línea)</span><textarea name="steps" defaultValue={toFieldValue(recipe?.steps)} className="field mt-2 min-h-28" placeholder={'Ej.\nCocinar el arroz.\nSaltear el pollo.'} /></label><div className="grid gap-4 sm:grid-cols-2"><label className="block text-sm font-bold">Tiempo <span className="font-normal text-ink/40 dark:text-cream/40">(opcional)</span><input name="time" defaultValue={recipe?.time || ''} className="field mt-2" placeholder="25 min" /></label><label className="block text-sm font-bold">Etiquetas <span className="font-normal text-ink/40 dark:text-cream/40">(separadas por comas)</span><input name="tags" defaultValue={recipe?.tags?.join(', ') || ''} className="field mt-2" placeholder="rápida, cena" /></label></div>{error && <p className="rounded-xl bg-coral/10 p-3 text-sm text-coral">{error}</p>}<button type="submit" disabled={loading} className="w-full rounded-full bg-moss py-3.5 text-sm font-bold text-white disabled:opacity-60">{loading ? 'Guardando...' : isEditing ? 'Guardar cambios' : 'Guardar receta'}</button></form></div></div>
}
